version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgre_project_001
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver_project_001
    restart: unless-stopped
    expose:
      - "8978"
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data_dev:/opt/cloudbeaver/workspace
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_project_001
    restart: unless-stopped
    environment:
      ENVIRONMENT: dev
      SERVER_ID: DEV-SERVER-1
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx_project_001
    restart: unless-stopped
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - cloudbeaver

volumes:
  db_data_dev:
  cloudbeaver_data_dev:
